version: '2'

services:

  php_apache:
    image: ambientum/php:7.0-apache
    container_name: php_apache
    volumes:
      - .:/var/www/app/public
    ports:
      - "8090:8080"
    links:
      - db
  
  db:
    image: mysql:5.7
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    ports:
      - "9090:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=biblioteca
