<?php if(isset($this->view->success)): ?>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <i class="fas fa-times"></i>
        </button>

        <?php
        foreach ($this->view->success as $message):
            ?>
            <i class="fas fa-check"></i>
            <?= $message; ?>
            <br>
        <?php endforeach; ?>
    </div>
<?php endif;?>
