<div class="container">

    <h1 class="h1"><?= $this->getPageTitle() ?></h1>

    <form action="/posts/store" method="post" accept-charset="utf-8">
        <div class="form-group">
            <label for="titulo">Título</label>
            <input type="text" name="titulo" class="form-control">
        </div>
        <div class="form-group">
            <label for="conteudo">Conteúdo</label>
            <textarea name="conteudo" class="form-control" rows="15"></textarea>
            <a href="/posts" class="btn btn-danger mt-2">Cancel</a>
            <button type="submit" class="btn btn-primary mt-2">Save</button>
        </div>
    </form>

</div>
