<div class="container">

    <h1 class="h1"><?= $this->getPageTitle(); ?></h1>
    <?php $this->loadView("Alerts/_errors"); ?>

    <form action="/posts/<?= $this->view->post->id; ?>/update" method="post" accept-charset="utf-8">
        <div class="form-group">
            <label for="titulo">Título</label>
            <input type="text" name="titulo" class="form-control"
                   value="<?= (isset($this->view->inputs['titulo'])) ? $this->view->inputs['titulo'] : $this->view->post->titulo ?>">
        </div>
        <div class="form-group">
            <label for="conteudo">Conteúdo</label>
            <textarea name="conteudo" class="form-control"
                      rows="15"><?= (isset($this->view->inputs['conteudo'])) ? $this->view->inputs['conteudo'] : $this->view->post->conteudo ?>
            </textarea>
            <a href="/posts" class="btn btn-danger mt-2">Cancelar</a>
            <button type="submit" class="btn btn-primary mt-2">Salvar</button>
        </div>
    </form>

</div>
