<div class="container">
    <h1 class="h1 my-3">
        <?=  $this->getPageTitle(); ?>
    </h1>
    <?php $this->loadView('Alerts/_success'); ?>
    <?php $this->loadView('Alerts/_errors'); ?>

    <form class="form-check-inline border rounded p-2" id="pageForm">
        <span class="mr-2">Livros por Página: </span>
        <div class="form-check form-check-inline ml-1 " name="firstRadio">
            <input class="form-check-input" type="radio" name="limit" id="numMax5" value="5">
            <label class="form-check-label" for="numMax5">5</label>
        </div>
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="limit" id="numMax10" value="10">
            <label class="form-check-label" for="numMax10">10</label>
        </div>
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="limit" id="numMax20" value="20">
            <label class="form-check-label" for="numMax20">20</label>
        </div>
    </form>
    <input type="hidden" name="pag" id="pag" value="0">
    <table class="table table-striped my-3">
        <thead class="thead-dark">
        <th> Titulo</th>
        <th> Autor</th>
        <th> Status</th>
        <th> <i class="fas fa-ellipsis-h"></i> </th>
        </thead>
        <tbody>
        <?php foreach ($this->view->livros as $livro): ?>
            <tr>
                <td><?= $livro->titulo;?></td>
                <td><?= $livro->autor;?></td>
                <td><?= $livro->status;?></td>
                <td><a class="btn" href="/livros/<?= $livro->id?>/show"><i class="fas fa-ellipsis-h"></i></a></td>
            </tr>

        <?php endforeach; ?>
        </tbody>
    </table>
    <nav aria-label="Page navigation">
        <ul class="pagination" id="ulPagination">
        </ul>
    </nav>
    <script src="/assets/js/pagination.js"></script>
</div>
